#!/usr/bin/python3
import sys


def factorize(number):
    factors = []
    for i in range(2, number // 2 + 1):
        if number % i == 0:
            factors.append((i, number // i))
    return factors


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename = sys.argv[1]

    try:
        with open(filename, 'r') as file:
            numbers = [int(line.strip()) for line in file]
    except FileNotFoundError:
        print(f"File '{filename}' not found.")
        sys.exit(1)
    except ValueError:
        print("Invalid input in the file. Only natural numbers greater than 1 are allowed.")
        sys.exit(1)

    for number in numbers:
        factors = factorize(number)
        for factor in factors:
            print(f"{number}={factor[0]}*{factor[1]}")

